version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:2023.12.4"
    volumes:
      - ha_conf:/config
      - ../custom_components:/config/custom_components
      - ./configuration.yaml:/config/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8123:8123"

volumes:
  ha_conf: